import { Component } from '@angular/core';
import { AuthenticateService } from '../services/auth.service';
import { CrudService } from '../services/crud.service';
import { Storage, getDownloadURL, ref, uploadBytesResumable } from '@angular/fire/storage';
import { MessageService } from '../services/message.service';
import { Router } from '@angular/router';
import { ILivro } from './acervo.interface';
import { IProduto } from './livros.interface';


@Component({
  selector: 'app-home',
    templateUrl: 'home.page.html',
      styleUrls: ['home.page.scss'],
      })
      export class HomePage {

      produtos: IProduto[] = [
        {
            nome: "delineador",
                quantidade: "1",
                    marca: "marimaria"
                      },
                        {
                            nome: "base liquida",
                                quantidade: "2",
                                    marca: "maybelline"
                                      },
                                        {
                                            nome: "batom matte",
                                                quantidade: "3",
                                                    marca: "mac"
                                                      },
                                                        {
                                                            nome: "rimel",
                                                                quantidade: "1",
                                                                    marca: "loreal"
                                                                      },
                                                                        {
                                                                            nome: "corretivo",
                                                                                quantidade: "2",
                                                                                    marca: "ruby rose"
                                                                                      },
                                                                                        {
                                                                                            nome: "po compacto",
                                                                                                quantidade: "1",
                                                                                                    marca: "vult"
                                                                                                      },
                                                                                                        {
                                                                                                            nome: "blush",
                                                                                                                quantidade: "2",
                                                                                                                    marca: "dailus"
                                                                                                                      },
                                                                                                                        {
                                                                                                                            nome: "iluminador",
                                                                                                                                quantidade: "1",
                                                                                                                                    marca: "quem disse berenice"
                                                                                                                                      },
                                                                                                                                        {
                                                                                                                                            nome: "primer facial",
                                                                                                                                                quantidade: "1",
                                                                                                                                                    marca: "tracta"
                                                                                                                                                      },
                                                                                                                                                        {
                                                                                                                                                            nome: "paleta de sombras",
                                                                                                                                                                quantidade: "1",
                                                                                                                                                                    marca: "anastasia"
                                                                                                                                                                      },
                                                                                                                                                                        {
                                                                                                                                                                            nome: "lapis de olho",
                                                                                                                                                                                quantidade: "4",
                                                                                                                                                                                    marca: "avon"
                                                                                                                                                                                      },
                                                                                                                                                                                        {
                                                                                                                                                                                            nome: "gloss labial",
                                                                                                                                                                                                quantidade: "2",
                                                                                                                                                                                                    marca: "fenty beauty"
                                                                                                                                                                                                      },
                                                                                                                                                                                                        {
                                                                                                                                                                                                            nome: "fixador de maquiagem",
                                                                                                                                                                                                                quantidade: "1",
                                                                                                                                                                                                                    marca: "nina secrets"
                                                                                                                                                                                                                      },
                                                                                                                                                                                                                        {
                                                                                                                                                                                                                            nome: "hidratante facial",
                                                                                                                                                                                                                                quantidade: "3",
                                                                                                                                                                                                                                    marca: "neutrogena"
                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                            nome: "esponja de maquiagem",
                                                                                                                                                                                                                                                quantidade: "5",
                                                                                                                                                                                                                                                    marca: "real techniques"
                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                            nome: "pincel de base",
                                                                                                                                                                                                                                                                quantidade: "2",
                                                                                                                                                                                                                                                                    marca: "macrilan"
                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                            nome: "pincel de blush",
                                                                                                                                                                                                                                                                                quantidade: "2",
                                                                                                                                                                                                                                                                                    marca: "belliz"
                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                            nome: "demaquilante",
                                                                                                                                                                                                                                                                                                quantidade: "1",
                                                                                                                                                                                                                                                                                                    marca: "bioderma"
                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                            nome: "agua micelar",
                                                                                                                                                                                                                                                                                                                quantidade: "2",
                                                                                                                                                                                                                                                                                                                    marca: "garnier"
                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                            nome: "protetor solar facial",
                                                                                                                                                                                                                                                                                                                                quantidade: "1",
                                                                                                                                                                                                                                                                                                                                    marca: "la roche posay"
                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                            nome: "lip balm",
                                                                                                                                                                                                                                                                                                                                                quantidade: "3",
                                                                                                                                                                                                                                                                                                                                                    marca: "nivea"
                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                      ];

                                                                                                                                                                                                                                                                                                                                                      livros: ILivro[] = [
                                                                                                                                                                                                                                                                                                                                                        { 
                                                                                                                                                                                                                                                                                                                                                            isbn: "123", 
                                                                                                                                                                                                                                                                                                                                                                titulo: "uma breve historia do tempo",
                                                                                                                                                                                                                                                                                                                                                                    categoria: [
                                                                                                                                                                                                                                                                                                                                                                          {nome: "cientifico"},
                                                                                                                                                                                                                                                                                                                                                                                {nome: "romance"},
                                                                                                                                                                                                                                                                                                                                                                                      {nome: "terror"}
                                                                                                                                                                                                                                                                                                                                                                                          ]
                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                  isbn: "124",
                                                                                                                                                                                                                                                                                                                                                                                                      titulo: "dom casmurro",
                                                                                                                                                                                                                                                                                                                                                                                                          categoria: [{nome: "romance"}]
                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                  isbn: "125",
                                                                                                                                                                                                                                                                                                                                                                                                                      titulo: "o pequeno principe",
                                                                                                                                                                                                                                                                                                                                                                                                                          categoria: [{nome: "infantil"}, {nome: "fantasia"}]
                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                  isbn: "126",
                                                                                                                                                                                                                                                                                                                                                                                                                                      titulo: "1984",
                                                                                                                                                                                                                                                                                                                                                                                                                                          categoria: [{nome: "ficcao"}, {nome: "distopia"}]
                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  isbn: "127",
                                                                                                                                                                                                                                                                                                                                                                                                                                                      titulo: "a revolucao dos bichos",
                                                                                                                                                                                                                                                                                                                                                                                                                                                          categoria: [{nome: "politico"}, {nome: "satira"}]
                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  isbn: "128",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      titulo: "o senhor dos aneis",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          categoria: [{nome: "fantasia"}]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  isbn: "129",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      titulo: "harry potter e a pedra filosofal",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          categoria: [{nome: "fantasia"}, {nome: "aventura"}]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  isbn: "130",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      titulo: "o codigo da vinci",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          categoria: [{nome: "suspense"}, {nome: "misterio"}]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  isbn: "131",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      titulo: "anjos e demonios",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          categoria: [{nome: "suspense"}]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  isbn: "132",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      titulo: "it a coisa",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          categoria: